### ISSUE TITLE
error when deploying

### ISSUE THREAD

**Issue by jdbuhl** [actions-on-google/actionssdk-say-number-nodejs#3]
Followed the directions listed [here](https://developers.google.com/actions/develop/sdk/getting-started) to deploy this action and received the following error when running `gcloud app deploy`:

```
Updating service [default]...failed.                                                                                                                       
ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:

> hello-action@0.0.1 start /app
> node app.js
module.js:328
    throw err;
    ^
Error: Cannot find module '/app/app.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! hello-action@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-action@0.0.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the hello-action package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls hello-action
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
```

It looks like it is looking for an app.js file that does not exists. Any help would be appreciated!

**Comment by LeonNicholls** [comment]
We are working on a fix.

**Comment by LeonNicholls** [comment]
Now fixed.

**Comment by jdbuhl** [comment]
I am now receiving the following error:

```
Updating service [default]...failed.                                                                                                                                                                        
ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:

> hello-action@0.0.1 start /app
> functions deploy sayNumber --trigger-http

sh: 1: functions: not found

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hello-action@0.0.1 start: `functions deploy sayNumber --trigger-http`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hello-action@0.0.1 start script 'functions deploy sayNumber --trigger-http'.
npm ERR! This is most likely a problem with the hello-action package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     functions deploy sayNumber --trigger-http
npm ERR! You can get their info via:
npm ERR!     npm owner ls hello-action
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
```

**Comment by smishra2** [comment]
You'll need to install the [Google Cloud Functions Emulator](https://github.com/GoogleCloudPlatform/cloud-functions-emulator). Follow the instructions [here](https://developers.google.com/actions/tools/fulfillment-hosting#deploy_locally).

**Comment by jdbuhl** [comment]
After installing the emulator I receive the following when I run `functions start`

```
lib/node_modules/@google-cloud/functions-emulator/bin/functions:62
let projectId = require('../src/utils/detectProjectId')(config.get('projectId'));
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by smishra2** [comment]
What version of Node.js are you using? Try `node -v` to find out. Try upgrading to a newer version of Node.js.

**Comment by jdbuhl** [comment]
I'm using v7.7.3
